### ISSUE TITLE
issue on installing?

### ISSUE THREAD

**Issue by killmasta93** [tiredofit/docker-leantime#7]
Hi 
Currently was trying to use the docker file but im getting 

`Notice: Undefined property: leantime\core\config::$defaultTimezone in /www/html/public/index.php on line 12`

```
version: '2'

services:

  leantime-app:
    image: tiredofit/leantime
    container_name: leantime-app
    links:
    - leantime-db
    volumes:
    ### If you want to perform customizations to the source and have access to it, then uncomment this line - This includes modules
    #- ./data:/www/html
    ### Or, if you just want to use Stock leantime and hold onto persistent files like cache and session use this, one or the other.
    - ./data:/data
    - ./logs/:/www/logs
    environment:
    - VIRTUAL_HOST=leantime.example.com
    - VIRTUAL_NETWORK=nginx-proxy
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=leantime.example.com
    - LETSENCRYPT_EMAIL=admin@example.com

    - CONTAINER_NAME=leantime-app

    - DB_HOST=leantime-db
    - DB_NAME=leantime
    - DB_USER=leantime
    - DB_PASS=leantime

    - SITE_URL=https://project.mydomain.com
    - SITE_NAME=Leantime
    - ADMIN_EMAIL=admin@example.com
    - ADMIN_PASS=admin
    - ADMIN_FIRST_NAME=Leantime
    - ADMIN_LAST_NAME=Administrator
    - COMPANY_NAME=Example Company

    - TIMEZONE=America/Vancouver

    networks:
      - proxy-tier
    restart: always

  leantime-db:
    image: tiredofit/mariadb
    container_name: leantime-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=password
      - DB_NAME=leantime
      - DB_USER=leantime
      - DB_PASS=leantime

      - CONTAINER_NAME=leantime-db
    networks:
      - proxy-tier
    restart: always

  leantime-db-backup:
    container_name: leantime-db-backup
    image: tiredofit/db-backup
    links:
     - leantime-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - CONTAINER_NAME=leantime-db-backup
      - DB_HOST=leantime-db
      - DB_TYPE=mariadb
      - DB_NAME=leantime
      - DB_USER=leantime
      - DB_PASS=leantime
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_CLEANUP_TIME=8640
      - COMPRESSION=BZ
      - MD5=TRUE
    networks:
      - proxy-tier
    restart: always


networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

thank you
